steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'coverage']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - gcp-cf-docsgen
    - --source=.
    - --trigger-bucket=gba-apis
    - --runtime=nodejs12
    - --region=europe-west1
    - --entry-point=onUpload
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - gcp-cf-docsgen-ondelete
    - --source=.
    - --trigger-resource=gba-apis
    - --trigger-event=google.storage.object.delete
    - --runtime=nodejs12
    - --region=europe-west1
    - --entry-point=onDelete