steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - gcp-cf-docsgen
    - --source=.
    - --trigger-bucket=gcp-api
    - --runtime=nodejs12
    - --set-env-vars POSTMAN_APIKEY=postmanApiKey
    - --entry-point=onUpload