openapi: 3.0.2
info:
  x-logo:
    url: "logo.png"
    backgroundColor: "#FFFFFF"
    altText: "LOGO"
  description: |
    # Introduction

    # OpenAPI Specification
    This API is documented in **OpenAPI format**

    # Cross-Origin Resource Sharing
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).
    And that allows cross-domain communication from the browser.
    All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    # Authentication

    Forms of authentication:
      - API Key
  title: TITLE
  version: 0.0.1
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    email: support@example.com
    url: http://example.com/support
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
externalDocs:
  description: Back to Api Portal
  url: https://online-bridge-hackathon.github.io/data-formats/
servers:
  - description: dev
    url: https://.hackathon.globalbridge.app/
tags:
  - name: ExampleTag
    description: 
components:
  responses:
    Default:
      description: Unexpected Error
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
    Success:
      description: Success
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Success"
  schemas:
    Error:
      description: Default Error Response Container
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    Success:
      description: Success
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
  requestBodies:
    exampleBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              hands:
                type: object
                properties:
paths:
  /api/:
    post:
      operationId: 
      responses:
        '200':
           "$ref": "#/components/responses/exampleBody"
        '400':
          "$ref": "#/components/responses/NotFound"
        '500':
          "$ref": "#/components/responses/Default"
        default:
          "$ref": "#/components/responses/Default"
      summary: 
      requestBody:
        $ref: "#/components/requestBodies/"
      tags: 
        - ExampleTag